// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using archolosDotNet.Database;

#nullable disable

namespace archolosDotNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224094016_consumable")]
    partial class consumable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("archolosDotNet.Models.BaseItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("additionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("sources")
                        .HasColumnType("text[]");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Consumable.ConsumableStat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("consumableId")
                        .HasColumnType("integer");

                    b.Property<int?>("duration")
                        .HasColumnType("integer");

                    b.Property<bool>("isPercentage")
                        .HasColumnType("boolean");

                    b.Property<bool>("isPermanent")
                        .HasColumnType("boolean");

                    b.Property<int>("stat")
                        .HasColumnType("integer");

                    b.Property<int?>("value")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("consumableId");

                    b.ToTable("ConsumableStats");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Consumable.Consumable", b =>
                {
                    b.HasBaseType("archolosDotNet.Models.BaseItem");

                    b.HasDiscriminator().HasValue("Consumable");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Consumable.ConsumableStat", b =>
                {
                    b.HasOne("archolosDotNet.Models.Item.Consumable.Consumable", "consumable")
                        .WithMany("consumableStats")
                        .HasForeignKey("consumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("consumable");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Consumable.Consumable", b =>
                {
                    b.Navigation("consumableStats");
                });
#pragma warning restore 612, 618
        }
    }
}
