// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using archolosDotNet.Database;

#nullable disable

namespace archolosDotNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227102712_recipe1")]
    partial class recipe1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("archolosDotNet.Models.Item.Armor.Armor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("additionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("sources")
                        .HasColumnType("text[]");

                    b.HasKey("id");

                    b.ToTable("Armors");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Armor.ArmorStatObj", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("armorId")
                        .HasColumnType("integer");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<int>("value")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("armorId");

                    b.ToTable("ArmorStats");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Consumable.Consumable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("additionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("sources")
                        .HasColumnType("text[]");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Consumables");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Consumable.ConsumableStat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("consumableId")
                        .HasColumnType("integer");

                    b.Property<int?>("duration")
                        .HasColumnType("integer");

                    b.Property<bool>("isPercentage")
                        .HasColumnType("boolean");

                    b.Property<bool>("isPermanent")
                        .HasColumnType("boolean");

                    b.Property<int>("stat")
                        .HasColumnType("integer");

                    b.Property<int?>("value")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("consumableId", "stat", "isPermanent")
                        .IsUnique();

                    b.ToTable("ConsumableStats");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Recipe.Recipe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("additionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<int>("requirement")
                        .HasColumnType("integer");

                    b.Property<int?>("requirementLevel")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("sources")
                        .HasColumnType("text[]");

                    b.Property<int>("targetId")
                        .HasColumnType("integer");

                    b.Property<int>("targetType")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Recipe.RecipeIngredient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("itemId")
                        .HasColumnType("integer");

                    b.Property<int>("itemType")
                        .HasColumnType("integer");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<int>("recipeId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("recipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Weapon.Weapon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("additionalInfo")
                        .HasColumnType("text");

                    b.Property<int?>("armorPiercing")
                        .HasColumnType("integer");

                    b.Property<int>("damage")
                        .HasColumnType("integer");

                    b.Property<int>("damageType")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<int?>("range")
                        .HasColumnType("integer");

                    b.Property<int>("skill")
                        .HasColumnType("integer");

                    b.Property<int?>("skillBonus")
                        .HasColumnType("integer");

                    b.Property<int?>("skillRequirement")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("sources")
                        .HasColumnType("text[]");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Armor.ArmorStatObj", b =>
                {
                    b.HasOne("archolosDotNet.Models.Item.Armor.Armor", null)
                        .WithMany("stats")
                        .HasForeignKey("armorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Consumable.ConsumableStat", b =>
                {
                    b.HasOne("archolosDotNet.Models.Item.Consumable.Consumable", null)
                        .WithMany("consumableStats")
                        .HasForeignKey("consumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Recipe.RecipeIngredient", b =>
                {
                    b.HasOne("archolosDotNet.Models.Item.Recipe.Recipe", null)
                        .WithMany("ingredients")
                        .HasForeignKey("recipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Armor.Armor", b =>
                {
                    b.Navigation("stats");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Consumable.Consumable", b =>
                {
                    b.Navigation("consumableStats");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Recipe.Recipe", b =>
                {
                    b.Navigation("ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
