// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using archolosDotNet.Database;

#nullable disable

namespace archolosDotNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("archolosDotNet.Models.Item.ArmorNS.Armor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("additionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("sources")
                        .HasColumnType("text[]");

                    b.HasKey("id");

                    b.ToTable("Armors");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.ArmorNS.ArmorStatObj", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("armorId")
                        .HasColumnType("integer");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<int>("value")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("armorId");

                    b.ToTable("ArmorStats");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.ConsumableNS.Consumable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("additionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("sources")
                        .HasColumnType("text[]");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Consumables");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.ConsumableNS.ConsumableStat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("consumableId")
                        .HasColumnType("integer");

                    b.Property<int?>("duration")
                        .HasColumnType("integer");

                    b.Property<bool>("isPercentage")
                        .HasColumnType("boolean");

                    b.Property<bool>("isPermanent")
                        .HasColumnType("boolean");

                    b.Property<int>("stat")
                        .HasColumnType("integer");

                    b.Property<int?>("value")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("consumableId", "stat", "isPermanent")
                        .IsUnique();

                    b.ToTable("ConsumableStats");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Miscellaneous.Misc", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("additionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("sources")
                        .HasColumnType("text[]");

                    b.HasKey("id");

                    b.ToTable("Miscs");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.RecipeNS.Recipe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("additionalInfo")
                        .HasColumnType("text");

                    b.Property<int?>("armorId")
                        .HasColumnType("integer");

                    b.Property<int?>("consumableId")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int?>("miscId")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<int>("requirement")
                        .HasColumnType("integer");

                    b.Property<int?>("requirementLevel")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("sources")
                        .HasColumnType("text[]");

                    b.Property<int?>("weaponId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("armorId");

                    b.HasIndex("consumableId");

                    b.HasIndex("miscId");

                    b.HasIndex("weaponId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.RecipeNS.RecipeIngredient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("armorId")
                        .HasColumnType("integer");

                    b.Property<int?>("consumableId")
                        .HasColumnType("integer");

                    b.Property<int?>("miscId")
                        .HasColumnType("integer");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<int>("recipeId")
                        .HasColumnType("integer");

                    b.Property<int?>("weaponId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("armorId")
                        .IsUnique();

                    b.HasIndex("consumableId");

                    b.HasIndex("miscId");

                    b.HasIndex("recipeId");

                    b.HasIndex("weaponId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.WeaponNS.Weapon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("additionalInfo")
                        .HasColumnType("text");

                    b.Property<int?>("armorPiercing")
                        .HasColumnType("integer");

                    b.Property<int>("damage")
                        .HasColumnType("integer");

                    b.Property<int>("damageType")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<int?>("range")
                        .HasColumnType("integer");

                    b.Property<int>("skill")
                        .HasColumnType("integer");

                    b.Property<int?>("skillBonus")
                        .HasColumnType("integer");

                    b.Property<int?>("skillRequirement")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("sources")
                        .HasColumnType("text[]");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("archolosDotNet.Models.UserNS.RefreshToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("expiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("token")
                        .IsUnique();

                    b.HasIndex("userId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("archolosDotNet.Models.UserNS.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .HasColumnType("text");

                    b.Property<string>("hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .HasColumnType("text");

                    b.Property<int>("role")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.ArmorNS.ArmorStatObj", b =>
                {
                    b.HasOne("archolosDotNet.Models.Item.ArmorNS.Armor", null)
                        .WithMany("stats")
                        .HasForeignKey("armorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.ConsumableNS.ConsumableStat", b =>
                {
                    b.HasOne("archolosDotNet.Models.Item.ConsumableNS.Consumable", null)
                        .WithMany("consumableStats")
                        .HasForeignKey("consumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.RecipeNS.Recipe", b =>
                {
                    b.HasOne("archolosDotNet.Models.Item.ArmorNS.Armor", "armor")
                        .WithMany()
                        .HasForeignKey("armorId");

                    b.HasOne("archolosDotNet.Models.Item.ConsumableNS.Consumable", "consumable")
                        .WithMany("recipes")
                        .HasForeignKey("consumableId");

                    b.HasOne("archolosDotNet.Models.Item.Miscellaneous.Misc", "misc")
                        .WithMany("recipes")
                        .HasForeignKey("miscId");

                    b.HasOne("archolosDotNet.Models.Item.WeaponNS.Weapon", "weapon")
                        .WithMany("recipes")
                        .HasForeignKey("weaponId");

                    b.Navigation("armor");

                    b.Navigation("consumable");

                    b.Navigation("misc");

                    b.Navigation("weapon");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.RecipeNS.RecipeIngredient", b =>
                {
                    b.HasOne("archolosDotNet.Models.Item.ArmorNS.Armor", "armor")
                        .WithOne("asIngredient")
                        .HasForeignKey("archolosDotNet.Models.Item.RecipeNS.RecipeIngredient", "armorId");

                    b.HasOne("archolosDotNet.Models.Item.ConsumableNS.Consumable", "consumable")
                        .WithMany("asIngredient")
                        .HasForeignKey("consumableId");

                    b.HasOne("archolosDotNet.Models.Item.Miscellaneous.Misc", "misc")
                        .WithMany("asIngredient")
                        .HasForeignKey("miscId");

                    b.HasOne("archolosDotNet.Models.Item.RecipeNS.Recipe", null)
                        .WithMany("ingredients")
                        .HasForeignKey("recipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("archolosDotNet.Models.Item.WeaponNS.Weapon", "weapon")
                        .WithMany("asIngredient")
                        .HasForeignKey("weaponId");

                    b.Navigation("armor");

                    b.Navigation("consumable");

                    b.Navigation("misc");

                    b.Navigation("weapon");
                });

            modelBuilder.Entity("archolosDotNet.Models.UserNS.RefreshToken", b =>
                {
                    b.HasOne("archolosDotNet.Models.UserNS.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.ArmorNS.Armor", b =>
                {
                    b.Navigation("asIngredient");

                    b.Navigation("stats");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.ConsumableNS.Consumable", b =>
                {
                    b.Navigation("asIngredient");

                    b.Navigation("consumableStats");

                    b.Navigation("recipes");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.Miscellaneous.Misc", b =>
                {
                    b.Navigation("asIngredient");

                    b.Navigation("recipes");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.RecipeNS.Recipe", b =>
                {
                    b.Navigation("ingredients");
                });

            modelBuilder.Entity("archolosDotNet.Models.Item.WeaponNS.Weapon", b =>
                {
                    b.Navigation("asIngredient");

                    b.Navigation("recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
